config/routes.rb
Rails.application.routes.draw do
  apipie
  mount Forem::Engine, :at => '/forums'

  get 'home/index'
  devise_for :users, path: '', path_names: { sign_in: 'home/index' }, controllers: { registrations: 'registrations' }
  root 'home#index'
  get 'home/water_quality'
  get 'home/display_settings'
  get 'home/create_model'
  get 'home/about'

  post 'user_preference/update'
  post 'trihalomethane_factor_model/create'
  post 'complete_factor_model/create'
  post 'trihalomethane_factor_model_preference/update'
  post 'complete_factor_model_preference/update'

end

app/views/shared/_footer.html.erb
<div id="footer">
  <p> Please contact ameglianmajor@greatwater.com with any questions, suggestions, or complaints.</p>
  <p><span class="copyright">&copy; GreatWater 2014</span></p>
</div>

app/views/shared/_header.html.erb
  <nav role="navigation" class="navbar navbar-default navbar-fixed-top main-nav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GreatWater", main_app.home_index_path, { class: 'navbar-brand' } %>
    </div>
    <!-- Collection of nav links and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Water Quality", main_app.home_water_quality_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Display Settings", main_app.home_display_settings_path %></li>
          <li><%= link_to "Create Model", main_app.home_create_model_path %></li>
        <% end %>
        <li><%= link_to "How It Works", main_app.home_about_path %></li>
        <li><%= link_to "Forum", main_app.forem_path %></li>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right login-link-top">
          <li class="welcome-user">Welcome <%= current_user.first_name %></li>
          <li><%= link_to "Sign out", main_app.destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right login-link-top">
          <li><a href="#" class="js-login-button">Log in</a></li>
          <li><a href="#" class="js-join-button">Sign up</a></li>
        </ul>
      <% end %>
    </div>
  </nav>

app/views/shared/_login_form.html.erb
<div class="login-dialog js-login-dialog" title="Log In">
  <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { id: 'login-form' }) do |f| %>
    <div class="login-field">
      <%= f.email_field :email, class: 'text ui-widget-content ui-corner-all form-text-input icon-email', placeholder: 'Email' %>
    </div>
    <div class="login-field">
      <%= f.password_field :password, class: 'text ui-widget-content ui-corner-all form-text-input icon-password', placeholder: 'Password' %>
    </div>
    <div class="js-password-reset forgot-password login-field"><a href="#">Forgot Password?</a></div>
    <div class='login-field modal-submit login-button'>
      <input type="submit" class="blue-button login-submit" value="Log In" />
    </div>
    <div class="login-field js-no-account no-account">
      <p>Don't have an account? <a href="">Sign up</a></p>
    </div>
  <% end %>
</div>

app/views/shared/_new_password.html.erb
<div class="new-password-dialog js-new-password-dialog" title="New Password">
    <div class="error js-new-password-error"></div>
    <form id="new-password-form">
      <div class="new-password-field">
        <input placeholder="Password" type="password" class='js-new-password-first form-text-input icon-password' />
      </div>
      <div class="new-password-field">
       <input placeholder="Verify Password" type="password" class='js-new-password-second form-text-input icon-password' />
      </div>
      <div class='new-password-field modal-submit'>
        <input type="submit" class="blue-button js-new-password-submit" />
      </div>
    </form>
</div>

app/views/shared/_password_reset_form.html.erb
<div class="password-reset-dialog js-password-reset-dialog" title="Password Reset">
  <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, id: 'password-reset-form' } ) do |f| %>
    <%= devise_error_messages! %>
    <div class="password-reset-field">
      <%= f.email_field :email, autofocus: true, class: 'text ui-widget-content ui-corner-all form-text-input icon-email' %>
    </div>
    <div class='password-reset-field modal-submit password-resetbutton'>
      <%= f.submit "Send Reset Link", class: "blue-button password-reset-submit js-password-reset-submit" %>
    </div>
  <% end %>
</div>

app/views/shared/_password_reset_notice.html.erb
<div class="reset-notice-dialog js-reset-notice-dialog">
  <p>Thanks. We sent you an email to reset your password.</p>
</div>

app/views/shared/_sign_up_form.html.erb
<div class="sign-up-dialog js-sign-up-dialog" title="Sign Up">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name) ) do |f| %>
    <div class="error sign-up-error js-sign-up-error"></div>
    <div class="sign-up-field">
      <%= f.text_field :first_name, class: 'text ui-widget-content ui-corner-all form-text-input icon-user js-user-name-first', placeholder: 'First Name' %>
    </div>
    <div class="sign-up-field">
      <%= f.text_field :last_name, class: 'text ui-widget-content ui-corner-all form-text-input icon-user js-user-name-last', placeholder: 'Last Name' %>
    </div>
    <div class="sign-up-field">
      <%= f.email_field :email, class: 'text ui-widget-content ui-corner-all form-text-input icon-email js-user-email', placeholder: 'Email Address' %>
    </div>
    <div class="sign-up-field">
      <%= f.password_field :password, class: 'text ui-widget-content ui-corner-all form-text-input icon-password js-user-password', placeholder: 'Password' %>
    </div>
    <div class="sign-up-field">
      <%= f.password_field :password_confirmation, class: 'text ui-widget-content ui-corner-all form-text-input icon-password js-user-password-verify', placeholder: 'Verify Password' %>
    </div>
    <div class='modal-submit sign-up-field sign-up-button'>
      <input type="submit" class="blue-button sign-up-submit js-sign-up-submit" value="submit" />
    </div>
  <% end %>
  <div class="has-account">
    <p>Have an account already? <a href="#" class="js-has-account">Log in</a></p>
  </div>
</div>